name: start_up_workspace
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  get: ^4.6.6
  shared_preferences: ^2.2.3
  http: ^1.2.1
  flutter_dotenv: ^5.1.0
  share_plus: ^9.0.0
  loading_plus: ^2.0.2
  awesome_notifications: ^0.9.3+1
  firebase_messaging: ^15.0.1
  package_info_plus: ^8.0.0
  internet_connection_checker: ^1.0.0+1
  upgrader: ^10.3.0
  in_app_review: ^2.0.9
  encrypt: ^5.0.3
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.3.0
  firebase_crashlytics: ^4.0.1
  firebase_analytics: ^11.0.1
  country_picker: ^2.0.26
  pinput: ^5.0.0
  material_design_icons_flutter: ^7.0.7296
  cloud_firestore: ^5.1.0
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  firebase_auth_platform_interface: ^7.4.2
  firebase_database: ^11.0.3


  #  rive: ^0.13.3
  #  cached_network_image: ^3.3.1
  #  transparent_image: ^2.0.1
  #  country_picker: ^2.0.25
  #  image_cropper: ^5.0.1
  #  image_picker: ^1.0.7
  #  geolocator: ^11.0.0
  #  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  import_sorter: ^4.6.0
  rename: ^3.0.2
  ########## import_sorter ##########
import_sorter:
  emojis: false
  comments: false

# dart run import_sorter:main
########## import_sorter ##########

########## rename ##########
#  dart pub global activate rename
#  rename getAppName --targets ios,android,macos,windows,linux
#  rename setAppName --targets ios,android,macos,windows,linux --value "App Name"
#  rename getBundleId --targets ios,android,macos,windows,linux
#  rename setBundleId --targets ios,android,macos,windows,linux --value "com.example.startUpWorkspace"

########## rename ##########

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  #  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icons/app_icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/app_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/app_icon.png"

#  flutter pub get
#  dart run flutter_launcher_icons

########## flutter_launcher_icons ##########

########## flutter_native_splash ##########
flutter_native_splash:
  color: "#ffffff"
  #background_image: "assets/background.png"
  image: assets/icons/app_icon.png
  #branding: assets/dart.png
  # bottom, bottomRight, bottomLeft
  #branding_mode: bottom
  #color_dark: "#042a49"
  #background_image_dark: "assets/dark-background.png"
  #image_dark: assets/splash-invert.png
  #branding_dark: assets/dart_dark.png
  android_12:
    color: "#ffffff"
    image: assets/icons/app_icon.png
  # dart run flutter_native_splash:create
  # dart run flutter_native_splash:remove
########## flutter_native_splash ##########

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env
    - assets/images/
    - assets/icons/
    # - assets/gifs/
    # - assets/sounds/
    # - assets/videos/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Black.ttf
          weight: 900
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo/Cairo-ExtraLight.ttf
          weight: 200
    # - family: Tajawal
    #   fonts:
    #     - asset: assets/fonts/Tajawal/Tajawal-ExtraBold.ttf
    #       weight: 800
    #     - asset: assets/fonts/Tajawal/Tajawal-Bold.ttf
    #       weight: 700
    #     - asset: assets/fonts/Tajawal/Tajawal-Medium.ttf
    #       weight: 500
    #     - asset: assets/fonts/Tajawal/Tajawal-Regular.ttf
    #       weight: 400
    #     - asset: assets/fonts/Tajawal/Tajawal-Light.ttf
    #       weight: 300
    #     - asset: assets/fonts/Tajawal/Tajawal-ExtraLight.ttf
    #       weight: 300